cmake_minimum_required(VERSION 3.20 FATAL_ERROR)
Project(OOP2 LANGUAGES CXX C)

add_subdirectory(01_convertFunc)
add_subdirectory(02_ptrClass)
add_subdirectory(03_funcClass)
add_subdirectory(04_template)
add_subdirectory(05_templateSpecialization)
add_subdirectory(06_templateTemplate)
add_subdirectory(07_reference)
add_subdirectory(08_virtualFunc)
add_subdirectory(09_Binding)
# add_subdirectory(const)
# add_subdirectory(C++OOP2)