cmake_minimum_required(VERSION 3.20 FATAL_ERROR)
Project(OOP3 LANGUAGES CXX C)

add_subdirectory(01_auto)
add_subdirectory(02_Uniform_Initialization)
add_subdirectory(03_Initialization_List)
add_subdirectory(04_Alias_Template)
add_subdirectory(05_Template_Template)
add_subdirectory(06_noexcept)
add_subdirectory(07_override)
add_subdirectory(08_final)
add_subdirectory(09_decltype)
add_subdirectory(10_lambda)
# add_subdirectory(1VariadicTemplates)